name: SITENAME
recipe: wordpress
config:
  php: '7.4'
  webroot: web
  xdebug: false
services:
  database:
    portforward: 50001
tooling:
  pull-db-production:
    service: appserver
    cmd:
      - wp db export -> db.sql --ssh=USER@HOST:PORT/path/to/current
      - wp db import db.sql
      - rm -f db.sql
      - wp search-replace https://SITENAME.com https://SITENAME.lndo.site --skip-columns=guid
      - wp plugin deactivate limit-login-attempts varnish-http-purge
  push-db-production:
    service: appserver
    cmd:
      - wp db export db.sql
      - scp -P PORT db.sql USER@HOST:/path/to/current
      - wp db import db.sql --ssh=USER@HOST:PORT/path/to/current
      - rm -f db.sql
      - wp search-replace https://SITENAME.lndo.site https://SITENAME.com --skip-columns=guid --ssh=USER@HOST:PORT/path/to/current
  pull-uploads-production:
    service: appserver
    cmd:
      - rsync -avz -e "ssh -p PORT" USER@HOST:/path/to/current/web/app/uploads/ ./web/app/uploads